#!/usr/bin/env python3
# trimming  - Trim nullLine of html
# 
# manontanto
#
import re
import sys

pre_post_regex = re.compile('(.*id="menu".*?\n)(.*)', re.DOTALL)
nl_regex = re.compile(r'\n\s*\n')

fn = input()
with open(fn, 'r') as infile:
    alltxt = infile.read()
    infile.close()
outlines = ''
mo = pre_post_regex.search(alltxt)
if mo: # menu行があれば
    outlines += mo.group(1) #前半部分
    m = nl_regex.search(mo.group(2))
    if not m:
        sys.exit()
    lines = mo.group(2).split('\n')
    for l in lines:
        if re.match(r'^\s*$', l): # Trim nullLine
            continue
        outlines += l + '\n'

    outfile = open(fn, 'w')
    outfile.write(outlines)
    outfile.close()

